# Generated by Django 3.1.5 on 2022-08-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='sunject',
            new_name='subject',
        ),
    ]
