# Generated by Django 3.1 on 2022-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220815_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
